### ISSUE TITLE
Request for Code Release

### ISSUE THREAD

**Issue by yunzinan** [Graph-and-Geometric-Learning/HEART#1]
Hello,

I recently read your paper, "*HEART: Learning better representation of EHR data with a heterogeneous relation-aware transformer*" published in *Journal of Biomedical Informatics*, and noticed that it mentions this GitHub repository as the location for the code implementation. However, the repository currently appears to be empty.

I am highly interested in your work and would like to study your implementation to better understand the methods and reproduce the results presented in the paper. Access to the code would also be invaluable for building upon your research and applying it to related problems.

Could you please **upload the code** as referenced in the paper? Making the code available would greatly benefit the research community.

Thank you!

**Comment by huangtinglin** [comment]
Thanks for your attention. The code is now available.
